# Рабочая тетрадь 2.
### Библиотека NumPy

NumPy (NumericalPython) - это библиотека Python с открытым
исходным кодом, которая используется практически во всех областях науки
и техники. Это универсальный стандарт для работы с числовыми данными в
Python.

Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:

pip install numpy

Чтобы начать использовать NumPy необходимо импортировать
соответствующую библиотеку:

import numpy as np

Основным объектом NumPy является однородный многомерный
массив (в numpy называется numpy.ndarray). Это многомерный массив
элементов (обычно чисел), одного типа.

Наиболее важные атрибуты объектов ndarray:

***ndarray.ndim*** - число измерений (чаще их называют "оси") массива.

***ndarray.shape*** - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.

***ndarray.size*** - количество элементов массива. Очевидно, равно
произведению всех элементов атрибута shape.

***ndarray.dtype*** - объект, описывающий тип элементов массива. Можно
определить dtype, используя стандартные типы данных Python. NumPy здесь
предоставляет целый букет возможностей, как встроенных, например: bool_,
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64,
object_, так и возможность определить собственные типы данных, в том
числе и составные.

***ndarray.itemsize*** - размер каждого элемента массива в байтах.

***ndarray.data*** - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.

Подробнее о массивах в NumPy можно найти в официальной
документации https://numpy.org/doc/stable/user/absolute_beginners.html


***Пример*** Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [1]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


***Пример*** Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19

In [2]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


***Пример*** Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [4]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.0057515229015414615 0.994700863241611 0.5283856116885964


***Пример*** Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [11]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


***Пример*** Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1


In [6]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


***Пример*** Отсортировать массив.

In [7]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


***Задача*** Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.


In [9]:
A = np.zeros(64).reshape(8, 8)
for i in range(0, 8):
    for j in range(0, 8):
        if (i + j)%2 != 0:
            A[i][j] = 1
print(A)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


***Задача*** Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [15]:
arr = np.zeros(25).reshape(5, 5)
A = np.arange(5)

for i in range(0, 5):
    arr[i] = A
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


***Пример*** Создать массив 3x3x3 со случайными значениями.

In [18]:
B = np.random.random((3, 3, 3))
print(B)

[[[4.38624592e-01 6.77133967e-01 9.57781984e-01]
  [2.98344390e-01 4.31278891e-02 9.19457451e-01]
  [8.64081882e-01 3.72838773e-01 1.31622192e-01]]

 [[9.97750457e-01 6.60749736e-01 8.03317692e-01]
  [8.27583275e-01 1.43241592e-01 8.44823748e-01]
  [5.83273308e-01 5.84728470e-01 6.55930343e-04]]

 [[8.47493714e-01 3.83984061e-01 1.58244395e-01]
  [4.19730890e-01 4.11669941e-01 2.65946230e-01]
  [9.72948614e-01 9.75528536e-01 4.97140222e-01]]]


***Задача*** Создать матрицу с 0 внутри, и 1 на границах.

In [23]:
D = np.zeros(25).reshape(5, 5)
for i in range(0, 5):
    for j in range(0, 5):
        if (i == 0) or (i == 4):
            D[i][j] = 1
        elif (j == 0) or (j == 4):
            D[i][j] = 1
print(D)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


***Задача*** Создайте массив и отсортируйте его по убыванию

In [26]:
arr = np.array([2, 1, 7, 5, 8, 4, 3, 9, 6])
print(np.sort(arr)[::-1])

[9 8 7 6 5 4 3 2 1]


***Задача*** Создайте матрицу, выведите ее форму, размер и размерность.

In [33]:
array = np.zeros(125).reshape(5, 5, 5)
print("Размерность: ", np.ndim(array))
print("Форма: ", np.shape(array))
print("Размер: ", np.size(array))

Размерность:  3
Форма:  (5, 5, 5)
Размер:  125


### Библиотека Pandas

Первым шагом в любом начинании в области машинного обучения
является введение исходных данных в систему. Исходные данные могут
вводиться вручную, содержаться в файле или храниться в интернете в каком-либо формате. Кроме того, часто требуется получить данные из нескольких
источников.

_Библиотека pandas_ – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.

_Библиотека pandas_ присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите
командной строке:

pip install pandas

Для импорта библиотеки используйте команду:

import pandas as pd

Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.

__Series__ – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.

__DataFrame__ – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами.


***Пример*** Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего). 


In [7]:
import pandas as pd
import numpy as np
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


***Пример*** Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [9]:
import pandas as pd
import numpy as np
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


***Пример*** Создайте новый фрейм данных

In [43]:
import pandas as pd
import numpy as np
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

***Пример*** Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [16]:
import pandas as pd
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

***Пример*** Пронализировать характеристики фрейма данных.

Одна из самых простых вещей, которые мы можем сделать после
загрузки данных, – это взглянуть на первые несколько строк с помощью
метода head. На последние строки можно посмотреть с помощью
функции tail. Мы также можем взглянуть на количество строк и
столбцов: dataframe.shape. Кроме того, используя метод describe, мы
можем получить описательную статистику для любых числовых
столбцов.

In [15]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [11]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [12]:
dataframe.shape

(1313, 6)

In [13]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

***Пример*** Выберите индивидуальные данные или срезы фрейма данных.

Для выбора одной или нескольких строк, либо значений, можно
использовать методы 1ос или iloc.

In [14]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

***Пример*** Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса

In [55]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

***Задача*** Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.


In [59]:
import math as m
x = pd.Series([5, 12], ['Ax', 'Bx'])
y = pd.Series([3, 7], ['Ay', 'By'])
s = m.sqrt((x['Bx'] - x['Ax'])**2 + (y['By'] - y['Ay'])**2)
print(s)

8.06225774829855


***Пример*** Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [20]:
url2 = 'https://raw.githubusercontent.com/akmand/datasets/main/airline_passenger_satisfaction.csv'
dataframe2 = pd.read_csv(url2)
dataframe2.head(5)

Gender      customer_type  age   type_of_travel customer_class  \
0    Male     Loyal Customer   13  Personal Travel       Eco Plus   
1    Male  disloyal Customer   25  Business travel       Business   
2  Female     Loyal Customer   26  Business travel       Business   
3  Female     Loyal Customer   25  Business travel       Business   
4    Male     Loyal Customer   61  Business travel       Business   

   flight_distance  inflight_wifi_service  departure_arrival_time_convenient  \
0              460                      3                                  4   
1              235                      3                                  2   
2             1142                      2                                  2   
3              562                      2                                  5   
4              214                      3                                  3   

   ease_of_online_booking  gate_location  ...  inflight_entertainment  \
0                       3              1  ...                       5   
1                       3              3  ...                       1   
2                       2              2  ...                       5   
3                       5              5  ...                       2   
4                       3              3  ...                       3   

   onboard_service  leg_room_service  baggage_handling  checkin_service  \
0                4                 3                 4                4   
1                1                 5                 3                1   
2                4                 3                 4                4   
3                2                 5                 3                1   
4                3                 4                 4                3   

   inflight_service  cleanliness  departure_delay_in_minutes  \
0                 5            5                          25   
1                 4            1                           1   
2                 4            5                           0   
3                 4            2                          11   
4                 3            3                           0   

   arrival_delay_in_minutes             satisfaction  
0                      18.0  neutral or dissatisfied  
1                       6.0  neutral or dissatisfied  
2                       0.0                satisfied  
3                       9.0  neutral or dissatisfied  
4                       0.0                satisfied  

[5 rows x 23 columns]

In [18]:
dataframe2.head(2)

Gender      customer_type  age   type_of_travel customer_class  \
0   Male     Loyal Customer   13  Personal Travel       Eco Plus   
1   Male  disloyal Customer   25  Business travel       Business   

   flight_distance  inflight_wifi_service  departure_arrival_time_convenient  \
0              460                      3                                  4   
1              235                      3                                  2   

   ease_of_online_booking  gate_location  ...  inflight_entertainment  \
0                       3              1  ...                       5   
1                       3              3  ...                       1   

   onboard_service  leg_room_service  baggage_handling  checkin_service  \
0                4                 3                 4                4   
1                1                 5                 3                1   

   inflight_service  cleanliness  departure_delay_in_minutes  \
0                 5            5                          25   
1                 4            1                           1   

   arrival_delay_in_minutes             satisfaction  
0                      18.0  neutral or dissatisfied  
1                       6.0  neutral or dissatisfied  

[2 rows x 23 columns]

In [19]:
dataframe2.tail(3)

Gender   customer_type  age   type_of_travel customer_class  \
129877  Female  Loyal Customer   17  Personal Travel            Eco   
129878    Male  Loyal Customer   14  Business travel       Business   
129879  Female  Loyal Customer   42  Personal Travel            Eco   

        flight_distance  inflight_wifi_service  \
129877              828                      2   
129878             1127                      3   
129879              264                      2   

        departure_arrival_time_convenient  ease_of_online_booking  \
129877                                  5                       1   
129878                                  3                       3   
129879                                  5                       2   

        gate_location  ...  inflight_entertainment  onboard_service  \
129877              5  ...                       2                4   
129878              3  ...                       4                3   
129879              5  ...                       1                1   

        leg_room_service  baggage_handling  checkin_service  inflight_service  \
129877                 3                 4                5                 4   
129878                 2                 5                4                 5   
129879                 2                 1                1                 1   

        cleanliness  departure_delay_in_minutes  arrival_delay_in_minutes  \
129877            2                           0                       0.0   
129878            4                           0                       0.0   
129879            1                           0                       0.0   

                   satisfaction  
129877  neutral or dissatisfied  
129878                satisfied  
129879  neutral or dissatisfied  

[3 rows x 23 columns]

In [21]:
dataframe2.shape

(129880, 23)

In [22]:
dataframe2.describe()

age  flight_distance  inflight_wifi_service  \
count  129880.000000    129880.000000          129880.000000   
mean       39.427957      1190.316392               2.728696   
std        15.119360       997.452477               1.329340   
min         7.000000        31.000000               0.000000   
25%        27.000000       414.000000               2.000000   
50%        40.000000       844.000000               3.000000   
75%        51.000000      1744.000000               4.000000   
max        85.000000      4983.000000               5.000000   

       departure_arrival_time_convenient  ease_of_online_booking  \
count                      129880.000000           129880.000000   
mean                            3.057599                2.756876   
std                             1.526741                1.401740   
min                             0.000000                0.000000   
25%                             2.000000                2.000000   
50%                             3.000000                3.000000   
75%                             4.000000                4.000000   
max                             5.000000                5.000000   

       gate_location  food_and_drink  online_boarding   seat_comfort  \
count  129880.000000   129880.000000    129880.000000  129880.000000   
mean        2.976925        3.204774         3.252633       3.441361   
std         1.278520        1.329933         1.350719       1.319289   
min         0.000000        0.000000         0.000000       0.000000   
25%         2.000000        2.000000         2.000000       2.000000   
50%         3.000000        3.000000         3.000000       4.000000   
75%         4.000000        4.000000         4.000000       5.000000   
max         5.000000        5.000000         5.000000       5.000000   

       inflight_entertainment  onboard_service  leg_room_service  \
count           129880.000000    129880.000000     129880.000000   
mean                 3.358077         3.383023          3.350878   
std                  1.334049         1.287099          1.316252   
min                  0.000000         0.000000          0.000000   
25%                  2.000000         2.000000          2.000000   
50%                  4.000000         4.000000          4.000000   
75%                  4.000000         4.000000          4.000000   
max                  5.000000         5.000000          5.000000   

       baggage_handling  checkin_service  inflight_service    cleanliness  \
count     129880.000000    129880.000000     129880.000000  129880.000000   
mean           3.632114         3.306267          3.642193       3.286326   
std            1.180025         1.266185          1.176669       1.313682   
min            1.000000         0.000000          0.000000       0.000000   
25%            3.000000         3.000000          3.000000       2.000000   
50%            4.000000         3.000000          4.000000       3.000000   
75%            5.000000         4.000000          5.000000       4.000000   
max            5.000000         5.000000          5.000000       5.000000   

       departure_delay_in_minutes  arrival_delay_in_minutes  
count               129880.000000             129487.000000  
mean                    14.713713                 15.091129  
std                     38.071126                 38.465650  
min                      0.000000                  0.000000  
25%                      0.000000                  0.000000  
50%                      0.000000                  0.000000  
75%                     12.000000                 13.000000  
max                   1592.000000               1584.000000

In [23]:
dataframe2.iloc[1:4]

Gender      customer_type  age   type_of_travel customer_class  \
1    Male  disloyal Customer   25  Business travel       Business   
2  Female     Loyal Customer   26  Business travel       Business   
3  Female     Loyal Customer   25  Business travel       Business   

   flight_distance  inflight_wifi_service  departure_arrival_time_convenient  \
1              235                      3                                  2   
2             1142                      2                                  2   
3              562                      2                                  5   

   ease_of_online_booking  gate_location  ...  inflight_entertainment  \
1                       3              3  ...                       1   
2                       2              2  ...                       5   
3                       5              5  ...                       2   

   onboard_service  leg_room_service  baggage_handling  checkin_service  \
1                1                 5                 3                1   
2                4                 3                 4                4   
3                2                 5                 3                1   

   inflight_service  cleanliness  departure_delay_in_minutes  \
1                 4            1                           1   
2                 4            5                           0   
3                 4            2                          11   

   arrival_delay_in_minutes             satisfaction  
1                       6.0  neutral or dissatisfied  
2                       0.0                satisfied  
3                       9.0  neutral or dissatisfied  

[3 rows x 23 columns]

In [25]:
dataframe2[dataframe2['Gender'] == 'Male'].head(2)

Gender      customer_type  age   type_of_travel customer_class  \
0   Male     Loyal Customer   13  Personal Travel       Eco Plus   
1   Male  disloyal Customer   25  Business travel       Business   

   flight_distance  inflight_wifi_service  departure_arrival_time_convenient  \
0              460                      3                                  4   
1              235                      3                                  2   

   ease_of_online_booking  gate_location  ...  inflight_entertainment  \
0                       3              1  ...                       5   
1                       3              3  ...                       1   

   onboard_service  leg_room_service  baggage_handling  checkin_service  \
0                4                 3                 4                4   
1                1                 5                 3                1   

   inflight_service  cleanliness  departure_delay_in_minutes  \
0                 5            5                          25   
1                 4            1                           1   

   arrival_delay_in_minutes             satisfaction  
0                      18.0  neutral or dissatisfied  
1                       6.0  neutral or dissatisfied  

[2 rows x 23 columns]

### Работа с числовыми данными

Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом
представления этих величин является численным (например, 150 студентов,
$529 392 продаж).

***Нормализация данных*** — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.

Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. В зависимости от используемой функции, их
можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.

На практике наиболее распространены следующие методы
нормализации признаков:

-***Минимакс*** – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;

-***Z-масштабирование*** данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.

При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.


***Пример*** Прошкалируйте числовой признак в диапазон между двумя значениями.

In [31]:
import numpy as np
import sklearn.preprocessing
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = sklearn.preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

***Пример*** Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [35]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = sklearn.preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [34]:
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", round(standardized.std()))

Среднее: 0
Стандартное отклонение: 1


***Пример*** Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.

In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

***Задача*** Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler